<?php

use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for database operations. This is
    | the connection which will be utilized unless another connection
    | is explicitly specified when you execute a query / statement.
    |
    */

    'default' => env('DB_CONNECTION', 'sqlite'),

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Below are all of the database connections defined for your application.
    | An example configuration is provided for each database system which
    | is supported by Laravel. You're free to add / remove connections.
    |
    */

    'connections' => [

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3308'),
            'database' => env('DB_DATABASE', 'db_warehouse'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],

        'puripagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.15.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'purimalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.15.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'amperapagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.19.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'amperamalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.19.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'alsutpagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.7.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'alsutmalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.7.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'bintaropagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.2.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'bintaromalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.2.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'sutamipagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.11.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'sutamimalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.11.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'jbtowerpagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.25.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'jbtowermalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.25.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'bekasipagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.18.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'bekasimalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.18.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'cilakipagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.4.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'cilakimalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.4.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'kuncitpagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.20.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'kuncitmalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.20.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'lbpagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.3.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'lbmalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.3.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'margondapagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.9.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'margondamalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.9.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'bogorpagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.5.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_grill'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'bogormalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.5.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_grill'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'sunterpagi' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.26.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'suntermalam' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.26.201'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_gril'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],

        'gatsu' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.8.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_grill'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'tb' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.13.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_grill'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
        'gading' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST_SECOND', '192.168.14.200'),
            'port' => env('DB_PORT_SECOND', '3306'),
            'database' => env('DB_DATABASE_SECOND', 'hachi_grill'),
            'username' => env('DB_USERNAME_SECOND', 'Service'),
            'password' => env('DB_PASSWORD_SECOND', '1'),
            'unix_socket' => env('DB_SOCKET_SECOND', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],

    ],


    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run on the database.
    |
    */

    'migrations' => [
        'table' => 'migrations',
        'update_date_on_publish' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer body of commands than a typical key-value system
    | such as Memcached. You may define your connection settings here.
    |
    */

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'username' => env('REDIS_USERNAME'),
            'password' => env('REDIS_PASSWORD'),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_CACHE_DB', '1'),
        ],

    ],

];
